name: WoW XML Template Namespacer
description: Namespaces XML template libraries so to eliminate collision risk with other AddOns.
branding:
  icon: code
  color: blue
inputs:
  name:
    description: 'A unique Identifier to your AddOn (normally, the name of your AddOn).'
    required: true
  pattern:
    description: 'The pattern string which will be replaced with $name'
    required: false
    default: 'MyAddOn'
  path:
    description: 'Path to the directory containing the XML templates that require namespacing'
    required: true
runs:
  using: composite
  steps:
    - run: |
        grep -rl ${{ inputs.pattern }} ${{ inputs.path }}/*.{xml,lua} | xargs sed -i "s/${{ inputs.pattern }}/${{ inputs.name }}/g"
      shell: bash
